<?php

namespace Marando\AstroDate;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-17 at 00:57:02.
 */
class TimeZoneTest extends \PHPUnit_Framework_TestCase {

  /**
   * @covers Marando\AstroDate\TimeZone::UT

   */
  public function testUT() {
    for ($o = -12; $o < 14; $o += 0.5) {
      $tz = TimeZone::UT($o, true);
      $this->assertEquals($o, $tz->offset(2451545.5));
      $this->assertEquals($o + 1, $tz->offset(2451595.5));

      $tz = TimeZone::UT($o, false);
      $this->assertEquals($o, $tz->offset(2451595.5));
    }
  }

  /**
   * @covers Marando\AstroDate\TimeZone::name
   */
  public function testName() {
    $this->assertEquals('EST', TimeZone::name('EST'));
  }

  /**
   * @covers Marando\AstroDate\TimeZone::UTC
   * @todo   Implement testUTC().
   */
  public function testUTC() {
    $utc = TimeZone::UTC();

    $this->assertEquals(0, $utc->offset(2451545.5));
    $this->assertEquals('UTC', $utc->name);
    $this->assertEquals(false, $utc->dst);
  }

  /**
   * @covers Marando\AstroDate\TimeZone::offset
   */
  public function testOffset() {
    for ($o = -12; $o < 14; $o += 0.5) {
      $tz = TimeZone::UT($o, true);
      $this->assertEquals($o, $tz->offset(2451545.5));
      $this->assertEquals($o + 1, $tz->offset(2451595.5));

      $tz = TimeZone::UT($o, false);
      $this->assertEquals($o, $tz->offset(2451595.5));
    }
  }

  /**
   * @covers Marando\AstroDate\TimeZone::__toString
   */
  public function test__toString() {
    $mst = TimeZone::name('mst');
    $this->assertEquals('MST', $mst->name);
  }

}
